config/routes.rb
Rails.application.routes.draw do

  resources :questions

  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  post "choices/create"
  post "choices/destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices

  def uncorrect
    choices.each {|c| c.correct = false}
  end

  def answer
    uncorrect
    choices.select {|c| c.correct}[0]
  end

  def answer= choice
    if !answer.nil?
      answer.correct = false
    end
    if choices.include? choice
      choice.correct = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @question = Question.find(params[:question])
    text = params[:text]
    correct = params[:correct] == '1'
    new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)

    if new.correct
      @question.answer = new
    end

    redirect_to question_path(@question)

  end

  def destroy
    @question = Question.find(params[:question])
    @choice = Choice.find(params[:choice])
    @choice.destroy

    redirect_to question_path(@question)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    @questions.sort {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html
      format.xml {render :xml => @questions}
    end
  end

  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def new
    @question = Question.new

    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(params_question)
    respond_to do |format|
      if @question.save
        format.html {redirect_to(@question, :notice => 'Pregunta agregada exitosamente')}
        format.xml {render :xml => @question, :status => :created, :location => @question}
      else
        format.html {render :action => 'new'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(params_question)
        format.html {redirect_to(@question, :notice => 'Pregunta actualizada exitosamente.')}
        format.xml {head :ok}
      else
        format.html {render :action => 'edit'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    respond_to do |format|
      format.html {redirect_to(question_url)}
      format.xml {head :ok}
    end
  end
  private
  def params_question
    params.require(:question).permit(:text)
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end

  def start
    total = params[:number].to_i
    all = Question.all.map {|x| x.id}
    session[:question] = all.sort_by {rand}[0..(total-1)]
    session[:total] = total
    session[:current] = 0
    session[:correct] = 0
    redirect_to :action => 'question'
  end

  def question
    @current= session[:current]
    @total = session[:total]
    if @current >= @total
      redirect_to :action => 'end'
      return
    end
    @question = Question.find(session[:question][@current])
    @choices = @question.choices.sort_by {rand}
    session[:question] = @question
    session[:choices] = @choices
  end

  def answer
    @current = session[:current]
    @total = session[:total]
    choiceid = params[:choice]
    @question = session[:question]
    @choices = session[:choices]
    @choice = choiceid ? Choice.find(choiceid):nil
    if @choice and @choice.correct
      @correct = true
      session[:correct] += 1
    else
      @correct = false
    end
    session[:current] += 1
  end

  def end
    @correct = session[:correct]
    @total = session[:total]
    @score = @correct * 100 / @total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/choices/create.html.erb
<h1>Choices#create</h1>
<p>Find me in app/views/choices/create.html.erb</p>

app/views/choices/destroy.html.erb
<h1>Choices#destroy</h1>
<p>Find me in app/views/choices/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, 'error') %>
  prohibited this question from beign saved:</h2>
<ul>
  <% @question.erros.full_messages.each do |msg| %>
  <li><%= msg %></li>
      <% end %>
</ul>
</div>
<% end %>
<div class="field">
  <%= f.label :text %><br />
  <%= f.text_area :text, :size => '50x3' %>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/questions/edit.html.erb
1>Editing question</h1>
<%= render 'form' %>
<%= link_to 'Show', @question %>
<%= link_to 'Back', question_path %>
<% content_for(:title) do %>
    Edit question
<% end %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>
<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path  %></p>
<table border="1">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th colspan="3">Opciones</th>
  </tr>
  <% @questions.each do|question| %>
      <tr>
        <td><%= question.text %></td>
        <td>
          <ul>
            <% question.choices.each do |choice| %>
                <li>
                  <%= choice.text %>
                  <% if choice.correct %>(correct)<% end %>
                </li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question)%></td>
        <td><%= link_to 'Destroy', question, :confirm => '¿Estas seguro?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<% content_for( :title) do %>
    All questions
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render 'form' %>
<%= link_to 'Back', questions_path %>
<% content_for(:title) do %>
    New Question
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>
<h4>Choices</h4>
<ul>
  <% @question.choices.find_each do |choice| %>
      <li>
        <%= choice.text %>
        <% if choice.correct%> (Correct)<% end %>
        <%= form_tag({:controller => 'choices', :action => 'destroy'} ) do %>
            <%= hidden_field_tag :question, @question.id %>
            <%= hidden_field_tag :choice, choice.id %>
            <%= submit_tag 'Delete' %>
        <% end %>
      </li>
  <% end %>
</ul>
<h5>New Choice</h5>
<%= form_tag({:controller => 'choices', :action=> 'create'}) do %>
    <%= hidden_field_tag :question, @question.id %>
    <%= label_tag :text, 'Text' %><br />
    <%= text_field_tag :text %><br />
    <%= check_box_tag :correct %><br />
    <br />
    <%= submit_tag 'Create' %>
<% end %>
<%= link_to 'Edit', edit_question_path(@question) %>
<%= link_to 'Back', questions_path %>
<% content_for(:title)do %>
    Question Details
<% end %>

app/views/quiz/answer.html.erb
<h1>Question <%= @current +1 %> of <%= @total %></h1>
<p id="question">
  <%= @question[:text] %>
</p>
<div id="feedback-choices">
  <% @choices.each do |choice| %>
  <% if(choice[:correct]) %>
      <p class="correct feedback-choice">
          <% elsif choice == @choice %>
      <p class="incorrect feedback-choice">
          <% else %>
      <p class="feedback-choice">
          <% end %>
      <%= choice[:text] %>
      </p>
      <% end %>
</div>
<p class="feedback">
  <% if @correct %>
  Correct!
      <% else %>
  Incorrect!
      <% end %>
</p>
<%= form_tag({:controller => 'quiz', :action =>'question'}) do %>
<div class="center">
  <%= submit_tag('Continue', :class=>'submit') %>
</div>
<% end %>
<% content_for(:title) do %>
Question <%= @current +1 %>of <%= @total %>
<%end%>

app/views/quiz/end.html.erb
<h1>Quiz Results</h1>
<p id="question">You answered correctly<%=@correct%> out of<%= @total%> questions.</p>
<p id="scorre"><%= @score%> %</p>
<%= form_tag({:controller => 'quiz', :action => 'index'}, :method => 'get') do %>
<div class="center">
  <%= submit_tag('Take another quiz', :class =>'submit')  %>
</div>
<% end %>
<% content_for (:title) do%>
Quiz Results
<% end %>

app/views/quiz/index.html.erb
<h1>Star Quiz</h1>
<%= form_tag({:controller => 'quiz', :action => 'start'}) do %>
<p><%= label_tag(:number, 'How many questions do you want in the quiz', :id => 'question') %></p>
<p class="center">
  <%= select_tag(:number, options_for_select((1..10).map{|x|[x,x]}), :id => 'count') %>
</p>
<div class="center">
  <%= submit_tag 'Star!', :class => 'submit' %>
</div>
<% end %>
<% content_for(:title) do %>
Start Quiz
<% end %>

app/views/quiz/question.html.erb
<h1>Quiz <%= @current + 1  %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>
<%= form_tag({:controller => 'quiz', :action => 'answer'}) do %>
<% @choices.each do |choice| %>
<p class="choice">
  <%= radio_button_tag(:choice, choice.id) %>
  <%= label_tag('choice_'.concat(choice.id.to_s).to_sym, choice.text) %>
</p>
<% end %>
<div class="center">
  <%= submit_tag('Continue', :class =>'submit') %>
</div>
<% end %>
<% content_for(:title) do %>
Question <%= @current +1  %> of <%= @total %>
<% end %>

app/views/quiz/start.html.erb
<h1>Quiz#start</h1>
<p>Find me in app/views/quiz/start.html.erb</p>